config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  root 'static_pages#home'
  get  '/help',    to:'static_pages#help'
  get  '/about',   to:'static_pages#about'
  get  '/contact', to:'static_pages#contact'
  
  get  '/signup',  to:'users#new'
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # resources :usersにネストを追加
  resources :users do
    # 以下でユーザーidが含まれるURLを扱えるようになる
    member do
      # :following, :followersのgetのルーティングを生成 
      get :following, :followers
    end
  end
  # account_activationsresourceのeditへのルーティングのみを生成
  resources :account_activations, only: [:edit]
  # password_resetsのnew、create、edit、updateのルーティングを生成 
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # micropostsのcreateとdestroyのルーティングを生成
  resources :microposts,          only: [:create, :destroy]
  # relationshipsのcreateとdestroyのルーティングを生成
  resources :relationships,       only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t('.errors count', errors_count: object.errors.count) %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<!--マイクロポスト投稿フォーム-->
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: t('.content_msg') %>
  </div>
  <%= f.submit t('.post_btn'), class: "btn btn-primary" %>
  <span class="picture">
    <!--acceptパラメータを使って許可したファイル形式をMIMEタイプで指定-->
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<!--jQueryでファイル合図の警告を出す-->
<script type="text/javascript">
  // id = "micropost_picture"を持つ要素の値が変更された時に実行
  $('#micropost_picture').bind('change', function() {
    // size_in_megabytesに代入→このファイルのサイズを取得してMBに換算（size/1024/1024）
    var size_in_megabytes = this.files[0].size/1024/1024;
    // size_in_megabytesが5より大きい時
    if (size_in_megabytes > 5) {
      // アラートを出す
      alert('5MBより大きな画像はアップロードできません');
    }
  });
</script>

app/views/shared/_stats.html.erb
<!--@userに @user もしくは@userがnilの場合current_user を代入-->
<!--プロフィールページとHomeページの両方に表示させるため現在のユーザーを取得-->
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <!--@userのfollowing数を（DB内で）count-->
      <%= @user.following.count %>
    </strong>
    <%= t('.following') %>
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <!--@userのfollowers数を（DB内で）count-->
      <%= @user.followers.count %>
    </strong>
    <%= t('.followers') %>
  </a>
</div>

app/views/shared/_user_info.html.erb
<!--サイドバーのユーザー情報部分-->
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t('.user_prf'), current_user %></span>
<span><%= t('.mc_count', user_microposts_count: current_user.microposts.count) %></span>